### ISSUE TITLE
Question about the release the weight of supervised models

### ISSUE THREAD

**Issue by najmehs** [MatthieuFP/zerommt#2]
Hi,
I was wondering if you are planning to release the weights for the VGAMT models you trained?
Thank you!

**Comment by MatthieuFP** [comment]
Hi, yes we plan to open source the VGAMT models for each language soon. I’ll ping you when done. Are you interested in the full VGAMT or only the one with CLIP features?

**Comment by MatthieuFP** [comment]
Hi @najmehs, sorry for the delay. You can download all the models here: https://drive.google.com/drive/folders/1IBc0fTA5JRf2t5aqfbZbhkJDspXdRHa-?usp=sharing

`vgamt_multilingual_cs-de-fr_siglip_only.pt' is the model we trained using SIGLIP features only, you should be able to use it with this codebase.

Best,
Matthieu
